### ISSUE TITLE
Design Bug caused by Atom Material Icons plugin

### ISSUE THREAD

**Issue by Sascha-Block** [mallowigi/a-file-icon-idea#384] opened 2023-07-20 15:38 UTC
**Describe the bug**
I want to zoom my IntelliJ IDE in order to record a easy readable session, but when zooming the spaces between projects menu lines are eliminated...

I tried to use different font sizes, but all the same...

**To Reproduce**

Make use of the zoom function or change to larger font size

**Expected Behavior**
A correct design also zooming the project navigation and using correct spaces between directory entries without interfeering or any restart needed

**Environment**
<!-- Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* MacOS - 13.4.1 (c) 
* IntelliJ IDEA 2023.1.4 (Ultimate Edition)
* Atom Material Icons 90.0.0

**Screenshots**
<img width="1214" alt="Bildschirmfoto 2023-07-20 um 17 38 11" src="https://github.com/mallowigi/a-file-icon-idea/assets/58812591/f1bb2db4-104c-48ec-b21c-2b0433f1e20c">

<img width="1299" alt="Bildschirmfoto 2023-07-20 um 17 55 10" src="https://github.com/mallowigi/a-file-icon-idea/assets/58812591/d52139fd-348c-4412-84c1-282fdc12a609">

**Comment by mallowigi** [comment] 2023-07-21 06:14
How to reproduce?

**Comment by Sascha-Block** [comment] 2023-07-21 06:33
With the given environment simply change the zoom factor from 100 % to e.g. 200 % 
It's the same if you change the font size from eg 11 to 16

**Comment by mallowigi** [comment] 2023-07-21 06:38
I didn't know about this feature but here is how it looks like in my end:

<img width="1840" alt="CleanShot 2023-07-21 at 09 38 21@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/5015756/36b910f7-800b-4a2a-8fc5-ea6ed4264c74">

**Comment by mallowigi** [comment] 2023-07-21 06:39
I disabled the plugin to make sure and it still looks like this:

![Uploading CleanShot 2023-07-21 at 09.38.58@2x.png…]()

**Comment by mallowigi** [comment] 2023-07-21 06:39
<img width="1796" alt="CleanShot 2023-07-21 at 09 38 58@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/5015756/61fa33ee-73f5-40d1-8cce-c5a8ead12a2a">

**Comment by mallowigi** [comment] 2023-07-21 06:41
And it looks like this when resizing to 100% back. So it's not a plugin issue.
<img width="1840" alt="CleanShot 2023-07-21 at 09 41 07@2x" src="https://github.com/mallowigi/a-file-icon-idea/assets/5015756/811df7a9-7e0f-4e9f-8c2b-1909848a0449">

**Comment by Sascha-Block** [comment] 2023-07-21 06:54
Informing JetBrains Support back, their answer was:

The issue seems to be caused by the Atom Material Icons plugin: https://plugins.jetbrains.com/plugin/10044-atom-material-icons.
As it is a third-party plugin, unfortunately we are not able to provide a fix for this issue.
Please file a new issue on the plugin's issue tracker: https://github.com/mallowigi/a-file-icon-idea/issues
 
As a temporary workaround, you can try to disable the plugin. The zoom should work as expected then.
Kind Regards,
Ivan
JetBrains Support

**Comment by mallowigi** [comment] 2023-07-21 07:14
Can you share my findings to their ticket? Thanks

**Comment by ivanpajic** [comment] 2023-07-21 08:27
@mallowigi 
Could you please share your IDE logs (**Help > Collect Logs and Diagnostic Data**) to check your environment details?
Also, please share a screenshot of your **Settings (`⌘ + ,` or `Ctrl + Alt + S`) > Appearance & Behavior > Appearance** page.
I couldn't reproduce your issue with the default settings and no custom plugins installed (v2023.1.4).

![idea64_P6zE2UamUX](https://github.com/mallowigi/a-file-icon-idea/assets/123973602/8913bb0d-0129-4329-941d-a26ccab77da5)

**Comment by Sascha-Block** [comment] 2023-07-21 09:13
Tell me what you're looking for, than I'll provide you the information. 
Due to the fact that diagnostics contain sensitive date I will not share that total package...

**Comment by ivanpajic** [comment] 2023-07-21 09:50
I created a new issue on JetBrains issue tracker: https://youtrack.jetbrains.com/issue/IDEA-326018.
Could you please [follow](https://www.jetbrains.com/help/youtrack/server/vote-for-issues.html#subscribe-to-updates-when-you-vote-for-issue) it to provide additional information?

**Comment by ivanpajic** [comment] 2023-07-21 09:54
> Tell me what you're looking for, than I'll provide you the information.
Due to the fact that diagnostics contain sensitive data I will not share that total package...

Are you able to reproduce the same issue as @mallowigi:

> I disabled the plugin to make sure and it still looks like this:
And it looks like this when resizing to 100% back. So it's not a plugin issue.

If you could share the information gathered from **Help > About > Copy and Close** and the screenshot from **Settings (`⌘ + ,` or `Ctrl + Alt + S`) > Appearance & Behavior > Appearance**. It would be great if you could share it on the YouTrack issue: https://youtrack.jetbrains.com/issue/IDEA-326018, to continue the troubleshooting there. Thanks!

**Comment by Sascha-Block** [comment] 2023-07-21 10:17
Sure. Thank you.Can you please tell me what to enter here?






Mit besten Grüßen,

Sascha Block
INZTITUT - INSPIRATION.INNOVATION.DIGITALISIERUNG

Büro Hamburg:   Tel. 040 - 87 93 88 70  · mobil: 0176 / 20 63 63 30
***@***.***   ·  www.inztitut.de

---
INZTITUT GmbH · Tel. 040 - 87 93 88 70 · ***@***.*** · www.inztitut.de · Beethovenstr. 11 · 22083 Hamburg
Amtsgericht Hamburg · HRB 168704 · USt-IdNr. DE282988280 · Geschäftsführer: Sascha BlockAm 21.07.2023 um 11:50 schrieb Ivan Pajic ***@***.***>:﻿
I created a new issue on JetBrains issue tracker: https://youtrack.jetbrains.com/issue/IDEA-326018.
Could you please follow it to provide additional information?

**Comment by ivanpajic** [comment] 2023-07-21 10:24
Sorry, not sure what exactly you are referring to. I don't see anything in your message: 
![image](https://github.com/mallowigi/a-file-icon-idea/assets/123973602/8b2ac4d5-3bfb-42ae-ac2a-f98e9362d9e4)

Is there some screenshot missing from it or?

**Comment by mallowigi** [comment] 2023-07-21 12:50
@ivanpajic I managed to reproduce. It's also happening on the Material Theme UI plugin, hence my confusion. It has to do with both plugins having the ability to customize the line height, but I need to find a way to listen to zoom changes.

**Comment by ivanpajic** [comment] 2023-07-26 07:44
@mallowigi 
Please check the answer from the developer: https://youtrack.jetbrains.com/issue/IDEA-326018/Zoom-function-causes-issues-in-the-UI#focus=Comments-27-7918292.0-0

> Currently, we don't have any special way of listening only scale change. However, you could listen for a `LafManagerListener.TOPIC`. The listener will be notified of the scale change as well.

```
busConnection.subscribe(LafManagerListener.TOPIC, LafManagerListener {
  //...
})
```

Also in every JComponent `updateUI()` is called. Overriding this method could help.

**Comment by Sascha-Block** [comment] 2023-08-14 14:04
@ivanpajic Please remove personal data like phone numbers from your screenshot. 

@mallowigi Do you have a solution for it or who's in care actually?

**Comment by mallowigi** [comment] 2023-08-14 14:45
I will take care of it when I have the time, but its not going to be soon

**Comment by mallowigi** [comment] 2023-08-19 07:52
Should be fixed next version hopefully.

**Closed by mallowigi** 2023-08-19 07:52 UTC
Labels: WIP
