### ISSUE TITLE
Folder icons not showing properly

### ISSUE THREAD

**Issue by serpro69** [mallowigi/a-file-icon-idea#217] opened 2021-09-16 06:43 UTC
**Describe the bug**
Folder icons are not showing. Only the folder in in which the current file is open has an icon, the rest are just arrows.

**To Reproduce**

N/A

**Expected Behavior**
Unless "hide folder icons" option is enabled, all folder icons should be visible.

This was working fine in version 38.0.0 and first broke in 40.0.0

**Environment**
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.16.3-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (41.0.0)
Current Desktop: Undefined

**Screenshots**

v41.0.0:
![image](https://user-images.githubusercontent.com/22973227/133562891-4ff10683-11e6-4d25-8b56-4ae9f963d770.png)

v38.0.0:
![image](https://user-images.githubusercontent.com/22973227/133563335-39c1a62e-1dc0-4e64-8f18-61069da3cba5.png)

settings:
![image](https://user-images.githubusercontent.com/22973227/133562950-e03a304d-1dd4-45b1-89c4-15f461f9e13d.png)

**Comment by mallowigi** [comment] 2021-09-16 17:28
duplicate of #218

**Closed by mallowigi** 2021-09-16 17:28 UTC
