### ISSUE TITLE
No display name is specified for configurable com.mallowigi.config.AtomHomeConfigurable in xml file

### ISSUE THREAD

**Issue by ForsakenHarmony** [mallowigi/a-file-icon-idea#382] opened 2023-07-12 17:08 UTC
**Describe the bug**

<details>
<summary>Stack Trace</summary>

```java
com.intellij.diagnostic.PluginException: No display name is specified for configurable com.mallowigi.config.AtomHomeConfigurable in xml file;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: com.mallowigi]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$new$0(GotoActionModel.java:81)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:120)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:105)
	at com.intellij.ide.util.gotoByName.GotoActionModel.getConfigurablesNames(GotoActionModel.java:378)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.processOptions(GotoActionItemProvider.java:148)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:94)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.lambda$fetchWeightedElements$4(ActionSearchEverywhereContributor.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.ide.actions.searcheverywhere.ActionSearchEverywhereContributor.fetchWeightedElements(ActionSearchEverywhereContributor.java:136)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

**To Reproduce**
- Open a project.

**Environment**
```
CLion 2023.2 EAP
Build #CL-232.8660.8, built on July 5, 2023
Runtime version: 17.0.7+7-b1000.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
GC: G1 Young Generation, G1 Old Generation

Non-Bundled Plugins:
    com.mallowigi (91.0.0)
```

**Comment by fburleigh** [comment] 2023-07-22 15:02
I see an IDE error with the same stacktrace as @ForsakenHarmony on opening any project:

```
com.intellij.diagnostic.PluginException: No display name is specified for configurable com.mallowigi.config.AtomSettingsConfigurable in xml file;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: com.mallowigi]
```

### Envionrment

```
IntelliJ IDEA 2023.2 RC (Ultimate Edition)
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
```
### Diagnosis (a guess!)

I first saw this complaint some months ago when I enabled JetBrains' feature, **Settings Sync**. With Sync enabled, I see this complaint; with Sync disabled, I do not.

**Comment by liamjones** [comment] 2023-07-25 07:49
This is now happening on the just-released version of WebStorm 2023.2 too.

**Comment by gitolicious** [comment] 2023-07-26 09:30
+1, **Settings Sync** is disabled

### Environment
```
IntelliJ IDEA 2023.2 RC (Ultimate Edition)
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Win11 Pro
```

**Comment by AllenAttuned** [comment] 2023-07-27 07:20
Also noticed after updating PyCharm to build `PY-232.8660.197` and DataGrip to build `DB-232.8660.111`. Exception will consistently be thrown when opening the IDEs' settings window.

**Comment by onukselcuk** [comment] 2023-07-27 08:10
This started happening after updating to Webstorm 2023.2

**Comment by mallowigi** [comment] 2023-07-27 12:32
Duplicate. It will be fixed as soon as i'm done with the current build.

**Closed by mallowigi** 2023-07-27 12:32 UTC

**Comment by gitolicious** [comment] 2023-07-28 06:26
Thanks for looking into it, @mallowigi. Can you link to the issue this is a duplicate of?
