### ISSUE TITLE
Disabling PSI icons stops working in IDEA 2019.2

### ISSUE THREAD

**Issue by lehvolk** [mallowigi/a-file-icon-idea#31] opened 2019-08-19 08:16 UTC
After upgrading to 2019.2 setting for disabling PSI icons is not working.

IDEA:
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
macOS 10.14.6

**Comment by mallowigi** [comment] 2019-08-20 21:10
I can't reproduce

**Comment by lehvolk** [comment] 2019-08-21 21:04
It's broken for Kotlin sources. Seems for other languages it's working fine. Thought that the problem is in Kotlin plugin.

**Comment by mallowigi** [comment] 2020-02-15 19:52
will be fixed next release

**Closed** 2020-02-15 19:54 UTC

**Comment by lehvolk** [comment] 2020-02-18 19:51
Thanks. Pretty nice plugin. I love it a lot.
