### ISSUE TITLE
Atom material exception

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/a-file-icon-idea#399] opened 2023-08-04 14:33 UTC
**Describe the bug**
Working normally with phpstorm an error shows up as in the attached screen shot

* OS (Windows) WSL
* phpstorm 2023.2

**Screenshots**
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/01d900ec-11f9-4d59-b1ad-db7ceea6be60)

**Comment by mallowigi** [comment] 2023-08-05 07:20
This screenshot doesn't help me at all. If you can't reproduce, I won't be able either.

Can you provide logs?

**Comment by Abdelraman** [comment] 2023-08-05 08:47
java.lang.IllegalStateException: Unexpected element while parsing cmd 'c' encountered token '-1e-4.000183' rest=-1e-4.0001(index=264 in input=m16.56 5.9994c-.0046.000383-.0087.00127-.01324.00165-.42659.03629-.83051.09268-1.1813.19192-.55415.166-1.0532.40447-1.494.71803-.4282.32278-.81705.72086-1.1697 1.1912-.34004.47956-.6824 1.0323-1.0224 1.6594-.12109.22868-.23331.42505-.35074.63696v.0017c-1e-4.000183-.0032-.000183-.0033 0l-1.3401 2.394-.005-.0017c-.23782.4425-.46149.84702-.66509 1.1978-.2141.36889-.45189.6815-.71637.93972-.26448.25822-.56659.45561-.90663.59394-.071945.02731-.1614.04195-.24155.06287-.0005144.000134-.00114-.000134-.00165 0h-.9877v2.4138h.98935v-.0017c.42844-.03628.83244-.09229 1.1846-.19192.55415-.166 1.0532-.40447 1.494-.71803.4282-.32278.8187-.72086 1.1713-1.1912.34005-.47956.68074-1.0323 1.0208-1.6594.12084-.22819.23523-.42557.3524-.63696l.0066.0017.0033-.005.0364-.06618h2.5296v.0017h1.125v-2.4072h-.33089v-.0017h-1.9787c.21975-.40713.43079-.78837.62041-1.1151.2141-.36889.45189-.6815.71637-.93972.26448-.25822.56659-.45561.90663-.59394.07046-.026754.15931-.041111.23824-.061214h.99266v-.00331h-.0017v-2.4105h-.97777v-.00165z)
	at com.github.weisj.jsvg.au.e(SourceFile:127)
	at com.github.weisj.jsvg.au.f(SourceFile:238)
	at com.github.weisj.jsvg.df.a(SourceFile:38)
	at com.github.weisj.jsvg.aX.a(SourceFile:60)
	at com.github.weisj.jsvg.be.build(SourceFile:91)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:115)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.github.weisj.jsvg.parser.ParsedElement.build(SourceFile:113)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.buildDocument(JSvgDocumentFactory.kt:109)
	at com.intellij.ui.svg.JSvgDocumentFactoryKt.createJSvgDocument(JSvgDocumentFactory.kt:36)
	at com.intellij.ui.svg.SvgKt.renderImage(svg.kt:294)
	at com.intellij.ui.svg.SvgKt.renderAndCache-rdQnj48(svg.kt:261)
	at com.intellij.ui.svg.SvgKt.access$renderAndCache-rdQnj48(svg.kt:1)
	at com.intellij.ui.svg.SvgKt.loadSvgAndCacheIfApplicable-F6nGey4(svg.kt:590)
	at com.intellij.ui.icons.ImageCacheKt.doLoadByDescriptor(imageCache.kt:290)
	at com.intellij.ui.icons.ImageCacheKt.loadByDescriptorWithoutCache(imageCache.kt:177)
	at com.intellij.ui.icons.ImageCacheKt.loadImage(imageCache.kt:139)
	at com.intellij.ui.icons.ImageDataByPathResourceLoader.loadImage(ImageDataByUrlLoader.kt:65)
	at com.intellij.ui.icons.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:313)
	at com.intellij.ui.icons.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:43)
	at com.intellij.ui.icons.CachedImageIcon.resolveActualIcon(CachedImageIcon.kt:158)
	at com.intellij.ui.icons.CachedImageIcon.getIconHeight(CachedImageIcon.kt:121)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:115)
	at com.mallowigi.icons.providers.DefaultFileIconProvider.getIcon(DefaultFileIconProvider.kt:41)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:83)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.access$loadIcon(AbstractFileIconProvider.kt:40)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider$getIconForAssociation$1.invoke(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda$0(AbstractFileIconProvider.kt:75)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:75)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:67)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:50)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:98)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:94)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:94)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:45)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.kt:279)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$result$1$1.invoke(DeferredIconImpl.kt:218)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$result$1$1.invoke(DeferredIconImpl.kt:218)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:38)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$invokeSuspend$$inlined$evaluateDeferred$1.invokeSuspend(IconDeferrerImpl.kt:91)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$invokeSuspend$$inlined$evaluateDeferred$1.invoke(IconDeferrerImpl.kt)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1$invokeSuspend$$inlined$evaluateDeferred$1.invoke(IconDeferrerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ui.DeferredIconImpl$scheduleCalculationIfNeeded$1.invokeSuspend(DeferredIconImpl.kt:374)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NumberFormatException: For input string: "-1e-4.000183"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:476)
	at com.github.weisj.jsvg.au.e(SourceFile:121)
	... 82 more

this is the error log, there is no a direct flow to reproduce, since it often (not always) shows up after saving and switching between taps,

**Comment by Abdelraman** [comment] 2023-08-05 08:48
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/86532048-320d-4f21-ab6c-96b2a4b9ddfa)
I don't know if this will help or not but i use multiple associations rather than the default ones

**Comment by mallowigi** [comment] 2023-08-05 08:49
Is it related to a custom icon or a provided one?

**Comment by Abdelraman** [comment] 2023-08-05 08:51
3 associations, 2 provided, 1 custom

**Comment by mallowigi** [comment] 2023-08-05 08:52
Can you send me the custom icons?

**Comment by Abdelraman** [comment] 2023-08-05 08:58
[db.zip](https://github.com/mallowigi/a-file-icon-idea/files/12266666/db.zip)

**Comment by mallowigi** [comment] 2023-08-05 09:26
Not this one, the PHP one

**Comment by Abdelraman** [comment] 2023-08-05 09:51
the php is using the predefined icons just changed the priority
 
default one
![Screenshot 2023-08-05 124730](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/5b0407f0-a48e-490c-bf3e-f7994b1bbdf7)

the updated one
![Screenshot 2023-08-05 124927](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/b98b5f4a-5608-4ee4-af37-18ddc56fe7a4)

**Comment by mallowigi** [comment] 2023-08-05 09:52
Hmm so you're not seeing the icons at all? That's a bummer...

I will try to find a windows machine and see if i can reproduce

**Comment by Abdelraman** [comment] 2023-08-06 19:56
restored to default associations, but still the issue happens frequently without any procedure to reproduce, this never happened in the previous versions. Thanks

**Comment by Abdelraman** [comment] 2023-08-16 22:16
Hello mallowigi, any updates for that.
Thanks.

**Comment by mallowigi** [comment] 2023-08-19 07:52
I have sent an update. It will be available soon. Once it's available please update and tell me if that fixed it. Thanks.

**Comment by Abdelraman** [comment] 2023-08-20 19:18
Thanks mallowigi,
I think the update not yet available on the marketplace 
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/e90cf4b8-e9ed-42ca-af6f-40c9d4153d5a)

**Comment by Abdelraman** [comment] 2023-08-20 19:33
apologies  I didn't get you comment concerning the chat regarding windows machines,  yes sure we can any time
as for the issue, I think it still persists

**Comment by mallowigi** [comment] 2023-08-23 09:02
So apparently your issue isn't solved. I can't reproduce on my end.

Do you have a project i can test on?

**Comment by Abdelraman** [comment] 2023-08-23 10:17
yes sure, this is a dummy project, that you can use,
https://bitbucket.org/abdeleid/ac/src/master/

I don't know if this issue can be related to caching, since I switch between version till the issue fixed 
will share also my settings
[settings.zip](https://github.com/mallowigi/a-file-icon-idea/files/12418037/settings.zip)

**Comment by mallowigi** [comment] 2023-08-23 11:11
Is that problem occuring on certain projects only or for all projects?

**Comment by Abdelraman** [comment] 2023-08-23 11:24
all projects, with non given scenario just shifting between taps and pressing ctrl + shift +n to go to specific file this issue occasionally happens

**Comment by Abdelraman** [comment] 2023-08-23 14:51
I am trying to reproduce the scenario, and it often happens after opening a new project and start typing in ctrl+shift+n window (search for file)
**mouser**

**Comment by Abdelraman** [comment] 2023-08-25 09:26
forget to mention that am using WSL (windows subsystem for linux)

**Comment by Abdelraman** [comment] 2023-08-26 21:38
Hello @mallowigi I was able to reproduce the issue, it too me some time, can we have a small chat ?

**Comment by Abdelraman** [comment] 2023-08-26 22:20
my friend after further more investigation, and checking multiple projects, it seems that files with .swf extension is causing the issue.
opening atom association and typing swf, php strom freezes and never comes back, a simple working around for now is that I set a specific random extension for .swf extension and it worked. 🤦‍♂️💃💃
thanks for all your efforts 👌 really appreciated

**Comment by mallowigi** [comment] 2023-08-27 09:12
I just tried it on mac and it doesn't reporduce...

**Comment by Abdelraman** [comment] 2023-08-27 09:41
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/9186d159-8187-44fe-9d78-bab456d7b1f7)
that happen when I type swf, no filters no scrolling can be done with these letters and tabs just got duplicated

am using windows,

_for the main issue_ 
can you download **ckeditor version 4** (yes it is an old version) it has .swf and try searching for this file, does the error show up ?

**java.lang.IllegalStateException: Unexpected element while parsing cmd 'c' encountered token '-1e-4.000183' rest=**

**Comment by mallowigi** [comment] 2023-08-27 09:51
just to be sure, can you send me the plugins you have installed? you can paste them from the about window

**Comment by Abdelraman** [comment] 2023-08-27 10:34
[ckeditor.zip](https://github.com/mallowigi/a-file-icon-idea/files/12447770/ckeditor.zip)

just extract this folder and open it in phpstorm and try to search for file **outputforflash**

**Comment by mallowigi** [comment] 2023-08-27 10:59
no no. I mean, can you show me the plugins you installed in your IDE

**Comment by Abdelraman** [comment] 2023-08-27 11:13
![image](https://github.com/mallowigi/a-file-icon-idea/assets/4821833/d508a1f2-8b45-4470-8f05-291537921438)
just these 4 plugins, the other plugins are installed by phpstorm itself

also to be informed, I have removed all the settings, downloaded plugins and got a clean install of phpstorm, and just atom material plugin installed, the issue still persists and finally it was the flash extensions **.swf**😢

**Comment by mallowigi** [comment] 2023-08-28 17:02
Sorry I'm closing this issue. I tried my best to reproduce and there is simply no possibility. The icon is completely fine, no background image or gradient or weird parameters, no typo and all.

If your workaround is doing the trick let's keep it at that.

**Closed by mallowigi** 2023-08-28 17:02 UTC

**Comment by Abdelraman** [comment] 2023-08-28 18:35
Tried to install it on intelJ and it is working **PERFECTLY** 2023.2.1 version, currently phpstorm is in 2023.2.0 version and am facing some issues related to performance, lets wait for version 2023.2.1 hoping that it is much more better and this issue will not rise again. really appreciate your great job

**Comment by jdreesen** [comment] 2023-08-28 18:52
https://blog.jetbrains.com/phpstorm/2023/08/phpstorm-2023-2-1-is-released/
