### ISSUE TITLE
Disabled icon associations are not loaded correctly after restarting

### ISSUE THREAD

**Issue by rster2002** [mallowigi/a-file-icon-idea#250] opened 2021-12-15 23:26 UTC
**Describe the bug**
I disabled the index association, but every time I restart it shows the icon again. If I then go into settings it shows as disabled, but doesn't seem to be applied. Enabling and disabling the association and then clicking 'apply' does work and gives the expected behavior.

**To Reproduce**

1. In the association settings, disable 'index' by clicking the checkbox on the left, then clicking 'apply';
2. Index files now don't use the index icon;
3. Restart the IDE;
4. Index files now do show the index icon even though it has been disabled
5. Open association settings again to see it's still disabled in the settings.

**Expected Behavior**
After restarting, the associations should work without having to enable and disable then after every restart.

**Environment**
PhpStorm 2021.3
Build #PS-213.5744.279, built on December 2, 2021
Runtime version: 11.0.13+7-b1751.19 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.4.1)
    com.fwdekker.randomness (2.7.4)
    dev.blachut.svelte.lang (0.21.1)
    com.mallowigi (50.2.0)
    ru.adelf.idea.dotenv (2021.3.0.213)

**Screenshots**
This screenshot is immediately after restarting.
<img width="997" alt="Screenshot 2021-12-16 at 00 25 46" src="https://user-images.githubusercontent.com/26026518/146280464-bddb9ec5-13c6-4a69-b781-5d55429abf18.png">

If you need any more info just ask. I'll be happy to help.

**Comment by mallowigi** [comment] 2021-12-16 06:29
Duplicate of https://github.com/mallowigi/a-file-icon-idea/issues/235

**Closed by mallowigi** 2021-12-16 06:29 UTC
