### ISSUE TITLE
javascript shows different icon

### ISSUE THREAD

**Issue by JackinJaxx** [mallowigi/a-file-icon-idea#342] opened 2023-01-10 18:50 UTC
**Describe the bug**
From the new update, the js icon changed, I don't know if that's the case or it's a bug

**To Reproduce**
Install the plugin.
Create a TS file.

**Expected Behavior**
JavaScript files have JavaScript icons.

**Environment**
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to Jose Alejandro Perez Chavez
Subscription is active until October 23, 2023.
For educational use only.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1966M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    tv.codely.codelytv-theme (2.2.2)
    com.github.copilot (1.1.38.2229)
    com.mallowigi (84.0.0)

Kotlin: 223-1.7.21-release-272-IJ8214.52

**Screenshots**
![image](https://user-images.githubusercontent.com/96992351/211636664-2a01a01c-a157-4776-ad95-d98cfa3a84c2.png)

**Comment by mallowigi** [comment] 2023-01-10 21:59
Literal duplicate of another bug posted today

**Closed** 2023-01-10 21:58 UTC
